# Generated by Django 5.0.4 on 2024-05-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Неизвестно', max_length=40, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('science-fiction', 'Научная фантастика'), ('adventure', 'Приключения'), ('horror', 'Ужасы')], default='Неизвестно', max_length=40, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Цена книги'),
        ),
        migrations.AddField(
            model_name='building',
            name='is_world_heritage',
            field=models.BooleanField(default=False, verbose_name='Объект всемрного наследия'),
        ),
        migrations.AddField(
            model_name='building',
            name='name',
            field=models.CharField(default='Без названия', max_length=40, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='building',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures', verbose_name='Фото здания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='building',
            name='architector',
            field=models.CharField(default='Неизвестно', max_length=40, verbose_name='Архитектор'),
        ),
        migrations.AlterField(
            model_name='building',
            name='foundation_date',
            field=models.DateField(verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='building',
            name='height',
            field=models.IntegerField(verbose_name='Высота'),
        ),
    ]
