# Generated by Django 5.0.4 on 2024-05-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_delete_building_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
